---
- name: Deploy webserver on Spacelift
  hosts: all
  gather_facts: true
  ignore_unreachable: true
  vars_files:
    - vars/default.yml
  tasks:
    - name: Install Apache packages on RedHat family
      become: true
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Create document root
      become: true
      ansible.builtin.file:
        state: directory
        dest: "{{ doc_root }}"
        mode: 0701

    - name: Create configuration file
      become: true
      ansible.builtin.template:
        src: spacelift.conf.j2
        dest: /etc/httpd/conf.d/spacelift.conf
        mode: 0644
      notify: Restart server

    - name: Copy web pages
      become: true
      ansible.builtin.template:
        src: index.html.j2
        dest: "{{ doc_root }}/index.html"

    - name: Ensure Apache is running on RedHat family
      become: true
      ansible.builtin.service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

  handlers:
    - name: Restart server
      become: true
      ansible.builtin.service:
        name: httpd
        state: restarted
